/*
 * Laboratory API
 *
 * Laboratory management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xmagulam@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lab

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type LabAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateLabAnalysis - Create a new laboratory analysis
	CreateLabAnalysis(ctx *gin.Context)

	// CreateSampleEvidence - Create a new sample evidence
	CreateSampleEvidence(ctx *gin.Context)

	// DeleteLabAnalysis - Delete laboratory analysis by ID
	DeleteLabAnalysis(ctx *gin.Context)

	// DeleteSampleEvidence - Delete sample evidence by ID
	DeleteSampleEvidence(ctx *gin.Context)

	// GetLabAnalysis - Get all laboratory analyses
	GetLabAnalysis(ctx *gin.Context)

	// GetLabAnalysisById - Get laboratory analysis by ID
	GetLabAnalysisById(ctx *gin.Context)

	// GetSampleEvidence - Get all sample evidences
	GetSampleEvidence(ctx *gin.Context)

	// GetSampleEvidenceById - Get sample evidence by ID
	GetSampleEvidenceById(ctx *gin.Context)

	// UpdateLabAnalysis - Update laboratory analysis by ID
	UpdateLabAnalysis(ctx *gin.Context)

	// UpdateSampleEvidence - Update sample evidence by ID
	UpdateSampleEvidence(ctx *gin.Context)
}

// partial implementation of LabAPI - all functions must be implemented in add on files
type implLabAPI struct {
}

func newLabAPI() LabAPI {
	return &implLabAPI{}
}

func (i *implLabAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodPost, "/lab/:laboratoryId/lab-analysis", i.CreateLabAnalysis)
	routerGroup.Handle(http.MethodPost, "/lab/:laboratoryId/sample-evidence", i.CreateSampleEvidence)
	routerGroup.Handle(http.MethodDelete, "/lab/:laboratoryId/lab-analysis/:analysisId", i.DeleteLabAnalysis)
	routerGroup.Handle(http.MethodDelete, "/lab/:laboratoryId/sample-evidence/:evidenceId", i.DeleteSampleEvidence)
	routerGroup.Handle(http.MethodGet, "/lab/:laboratoryId/lab-analysis", i.GetLabAnalysis)
	routerGroup.Handle(http.MethodGet, "/lab/:laboratoryId/lab-analysis/:analysisId", i.GetLabAnalysisById)
	routerGroup.Handle(http.MethodGet, "/lab/:laboratoryId/sample-evidence", i.GetSampleEvidence)
	routerGroup.Handle(http.MethodGet, "/lab/:laboratoryId/sample-evidence/:evidenceId", i.GetSampleEvidenceById)
	routerGroup.Handle(http.MethodPut, "/lab/:laboratoryId/lab-analysis/:analysisId", i.UpdateLabAnalysis)
	routerGroup.Handle(http.MethodPut, "/lab/:laboratoryId/sample-evidence/:evidenceId", i.UpdateSampleEvidence)
}
