/*
 * Laboratory API
 *
 * Laboratory management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xmagulam@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lab

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type SampleEvidencesAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateSampleEvidence - Create a new sample evidence
	CreateSampleEvidence(ctx *gin.Context)

	// DeleteSampleEvidence - Delete sample evidence by ID
	DeleteSampleEvidence(ctx *gin.Context)

	// GetSampleEvidence - Get all sample evidences
	GetSampleEvidence(ctx *gin.Context)

	// GetSampleEvidenceById - Get sample evidence by ID
	GetSampleEvidenceById(ctx *gin.Context)

	// UpdateSampleEvidence - Update sample evidence by ID
	UpdateSampleEvidence(ctx *gin.Context)
}

// partial implementation of SampleEvidencesAPI - all functions must be implemented in add on files
type implSampleEvidencesAPI struct {
}

func newSampleEvidencesAPI() SampleEvidencesAPI {
	return &implSampleEvidencesAPI{}
}

func (t *implSampleEvidencesAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodPost, "/lab/:laboratoryId/sample-evidence", t.CreateSampleEvidence)
	routerGroup.Handle(http.MethodDelete, "/lab/:laboratoryId/sample-evidence/:evidenceId", t.DeleteSampleEvidence)
	routerGroup.Handle(http.MethodGet, "/lab/:laboratoryId/sample-evidence", t.GetSampleEvidence)
	routerGroup.Handle(http.MethodGet, "/lab/:laboratoryId/sample-evidence/:evidenceId", t.GetSampleEvidenceById)
	routerGroup.Handle(http.MethodPut, "/lab/:laboratoryId/sample-evidence/:evidenceId", t.UpdateSampleEvidence)
}
