/*
 * Laboratory API
 *
 * Laboratory management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xmagulam@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lab

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type LabsAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateLab - Saves new lab definition
	CreateLab(ctx *gin.Context)

	// DeleteLaboratory - Deletes specific laboratory
	DeleteLaboratory(ctx *gin.Context)
}

// partial implementation of LabsAPI - all functions must be implemented in add on files
type implLabsAPI struct {
}

func newLabsAPI() LabsAPI {
	return &implLabsAPI{}
}

func (t *implLabsAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodPost, "/lab", t.CreateLab)
	routerGroup.Handle(http.MethodDelete, "/lab/:laboratoryId", t.DeleteLaboratory)
}
